name = "developer-tools-worker"
main = "src/index.ts"
compatibility_date = "2024-12-31"

# R2 Storage bindings
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "developer-tools-files"

# KV Storage for URL mappings and metadata
[[kv_namespaces]]
binding = "URL_MAPPINGS"
id = "url_mappings_preview"
preview_id = "url_mappings_preview"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "analytics_preview"
preview_id = "analytics_preview"

# Environment variables
[vars]
ALLOWED_ORIGINS = "*"
MAX_FILE_SIZE = "104857600"  # 100MB
DEFAULT_URL_EXPIRY = "86400" # 24 hours in seconds

# Required secrets (set with: wrangler secret put SECRET_NAME)
# ADMIN_PASSWORD - Admin panel password
# JWT_SECRET - JWT signing secret